name: g_recaptcha_v3_example
description: Demonstrates how to use the g_recaptcha_v3 plugin.

publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  g_recaptcha_v3:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
