name: g_recaptcha_v3
description: Google reCAPTCHA v3 plugin for Flutter Web. A Google reCAPTCHA is a free service that protects your website from spam and abuse.
version: 0.0.5
homepage: https://github.com/bharathraj-e/g_recaptcha_v3

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GRecaptchaV3PlatformInterface
        fileName: g_recaptcha_v3_web.dart

